INSERT INTO units (unit_id, name, category, class, image_path, description, stats) VALUES
-- ========== RECON CATEGORY ==========
('recon_inf', 'Recon Operator', 'recon', 'infantry', '../images/recon/recon_inf.png', 'Lightly armed scouts trained for stealth, surveillance, and gathering battlefield intelligence', '{"health": 70, "speed": 8, "attackRange": 120, "damage": 15, "vision": 200}'),
('recon_raven', 'RQ-11 Raven (USA)', 'recon', 'uav', '../images/recon/recon_raven.png', 'A lightweight, man-portable UAV for short-range battlefield reconnaissance. Commonly deployed with infantry squads.', '{"health": 40, "speed": 12, "attackRange": 0, "damage": 0, "vision": 250}'),
('recon_puma', 'RQ-20 Puma (USA)', 'recon', 'uav', '../images/recon/recon_puma.png', 'A hand-launched UAV with high endurance for tactical reconnaissance. Provides real-time battlefield awareness.', '{"health": 50, "speed": 10, "attackRange": 0, "damage": 0, "vision": 300}'),
('recon_heron', 'IAI Heron (Israel)', 'recon', 'uav', '../images/recon/recon_heron.png', 'A long-endurance medium-altitude UAV used for reconnaissance and surveillance missions. Widely adopted by multiple countries for battlefield intelligence gathering.', '{"health": 80, "speed": 15, "attackRange": 0, "damage": 0, "vision": 400}'),
('recon_eagle', 'MQ-1C Gray Eagle (USA)', 'recon', 'uav', '../images/recon/recon_eagle.png', 'A tactical UAV capable of both reconnaissance and light strike missions. Operated extensively by the US Army.', '{"health": 90, "speed": 14, "attackRange": 150, "damage": 25, "vision": 350}'),
('recon_orion', 'Orion-E (Russia)', 'recon', 'uav', '../images/recon/recon_orion.png', 'A medium-altitude long-endurance UAV designed for reconnaissance, surveillance, and target acquisition.', '{"health": 85, "speed": 13, "attackRange": 0, "damage": 0, "vision": 380}'),
('recon_global', 'RQ-4 Global Hawk (USA)', 'recon', 'uav', '../images/recon/recon_global.png', 'A high-altitude, long-endurance UAV specialized in strategic reconnaissance. Provides wide-area surveillance for extended missions.', '{"health": 100, "speed": 20, "attackRange": 0, "damage": 0, "vision": 500}'),
('recon_tb2', 'Bayraktar TB2 (Turkey)', 'recon', 'uav', '../images/recon/recon_tb2.png', 'A medium-altitude UAV designed for reconnaissance and light attack roles. Known for its effectiveness and cost-efficiency.', '{"health": 75, "speed": 11, "attackRange": 120, "damage": 20, "vision": 320}'),
('recon_wingloong', 'Wing Loong II (China)', 'recon', 'uav', '../images/recon/recon_wingloong.png', 'A Chinese medium-altitude UAV used for both surveillance and limited strike operations. Exported widely to allied nations.', '{"health": 85, "speed": 12, "attackRange": 130, "damage": 22, "vision": 340}'),
('recon_harfang', 'EADS Harfang (France/EU)', 'recon', 'uav', '../images/recon/recon_harfang.png', 'A European adaptation of the Israeli Heron UAV, designed for surveillance and intelligence gathering. Used by French and NATO forces.', '{"health": 80, "speed": 13, "attackRange": 0, "damage": 0, "vision": 370}'),
('recon_blackjack', 'RQ-21 Blackjack (USA)', 'recon', 'uav', '../images/recon/recon_blackjack.png', 'A small tactical UAV used by the US Marines and Navy. Supports naval and coastal reconnaissance operations.', '{"health": 60, "speed": 10, "attackRange": 0, "damage": 0, "vision": 280}'),
('recon_korshun', 'Tu-300 Korshun (Russia)', 'recon', 'uav', '../images/recon/recon_korshun.png', 'A tactical reconnaissance UAV developed by Russia. Primarily used for battlefield surveillance missions.', '{"health": 70, "speed": 11, "attackRange": 0, "damage": 0, "vision": 290}'),

-- ========== ROBOTICS CATEGORY ==========
('rob_emav', 'EMAV-LW30 UGV (USA)', 'robotics', 'ground', '../images/robotics/rob_emav.png', 'Expeditionary Modular Autonomous Vehicle with Light Weapon 30mm system, featuring advanced AI navigation, remote operation capability, and modular payload options for reconnaissance and fire support missions.', '{"health": 250, "speed": 5, "attackRange": 200, "damage": 40, "armor": 50}'),
('rob_themis', 'THEMIS UGV (Estonia)', 'robotics', 'ground', '../images/robotics/rob_themis.png', 'Modular unmanned ground vehicle platform by Milrem Robotics, designed for various military applications including cargo transport, casualty evacuation, and weaponized combat support with open architecture for mission-specific modules.', '{"health": 300, "speed": 6, "attackRange": 180, "damage": 35, "armor": 60}'),

-- ========== INFANTRY CATEGORY ==========
('inf_spet', 'Spetsnaz Operator (Russia)', 'infantry', 'special_forces', '../images/infantry/infantry_spetsnaz.png', 'Elite special forces operator trained for reconnaissance, direct action, and counter-terrorism missions with expertise in unconventional warfare and advanced weapons handling.', '{"health": 120, "speed": 7, "attackRange": 100, "damage": 25, "stealth": 8}'),
('inf_ranger', 'US Army Rangers Operator (USA)', 'infantry', 'special_forces', '../images/infantry/infantry_ranger.png', 'Elite light infantry special operations force specializing in direct action, airfield seizure, reconnaissance, and personnel recovery missions in high-risk environments.', '{"health": 125, "speed": 7.5, "attackRange": 110, "damage": 26, "stealth": 7}'),
('inf_sas', 'SAS Operator (UK)', 'infantry', 'special_forces', '../images/infantry/infantry_sas.png', 'Elite special forces operator from the Special Air Service, specializing in counter-terrorism, hostage rescue, covert reconnaissance, and direct action missions worldwide.', '{"health": 120, "speed": 7.2, "attackRange": 105, "damage": 25, "stealth": 9}'),
('inf_demolition', 'USMC Demolition Operator (USA)', 'infantry', 'combat_engineer', '../images/infantry/infantry_demolition.png', 'Highly trained Marine Corps combat engineer specializing in explosive ordnance disposal, vehicles destruction, and tactical demolition in support of amphibious and ground operations.', '{"health": 130, "speed": 6, "attackRange": 80, "damage": 40, "explosives": 10}'),
('inf_usmc', 'USMC Assault Operator (USA)', 'infantry', 'assault', '../images/infantry/infantry_usmc.png', 'Marine Corps infantry specialist trained in close-quarters battle, room clearing, and direct action operations, serving as the primary assault element in amphibious and urban combat.', '{"health": 140, "speed": 6.5, "attackRange": 90, "damage": 30, "courage": 8}'),
('inf_force', 'USMC Force Recon (USA)', 'infantry', 'recon', '../images/infantry/infantry_recon.png', 'Elite Marine Corps special operations capable unit specializing in deep reconnaissance, direct action, and advanced amphibious operations behind enemy lines.', '{"health": 115, "speed": 8, "attackRange": 120, "damage": 22, "stealth": 9}'),
('inf_sniper', 'USMC Scout Sniper (USA)', 'infantry', 'sniper', '../images/infantry/infantry_sniper.png', 'Highly trained Marine marksmen specializing in long-range precision engagement, intelligence gathering, and providing overwatch for infantry operations in various combat environments.', '{"health": 100, "speed": 5.5, "attackRange": 250, "damage": 60, "accuracy": 10}'),
('inf_vdv', 'VDV Paratrooper (Russia)', 'infantry', 'airborne', '../images/infantry/infantry_vdv.png', 'Elite Russian Airborne Forces operator trained for rapid deployment, air assault operations, and securing strategic objectives behind enemy lines with specialized airborne equipment.', '{"health": 125, "speed": 7, "attackRange": 95, "damage": 24, "mobility": 8}'),
('inf_mars3', 'PLAGF SOF with MARS 3 (China)', 'infantry', 'special_forces', '../images/infantry/infantry_mars3.png', 'Elite special operations operator equipped with advanced MARS 3 integrated combat system featuring networked communications, enhanced situational awareness, and digital battlefield integration capabilities.', '{"health": 130, "speed": 6.8, "attackRange": 115, "damage": 27, "tech": 9}'),
('inf_hololens', 'US SOF with HoloLens (USA)', 'infantry', 'special_forces', '../images/infantry/infantry_hololens.png', 'Special Operations Forces operator equipped with Microsoft HoloLens augmented reality system for enhanced situational awareness, target identification, and real-time battlefield data integration.', '{"health": 120, "speed": 7, "attackRange": 105, "damage": 24, "tech": 10}'),
('inf_cobra', 'COBRA Operator (Brazil)', 'infantry', 'special_forces', '../images/infantry/infantry_cobra.png', 'Next-generation Brazilian special operations platform designed for integrated network-centric warfare, featuring advanced technology, real-time data sharing, and enhanced C4ISR capabilities for modern asymmetric combat environments.', '{"health": 125, "speed": 7.3, "attackRange": 110, "damage": 26, "tech": 8}'),
('inf_idz', 'IdZ-eS Soldier System (Germany)', 'infantry', 'future_soldier', '../images/infantry/infantry_idz.png', 'Advanced German future soldier program featuring integrated networked combat systems, enhanced situational awareness, weapon interfaces, and comprehensive protective equipment for modern networked warfare.', '{"health": 135, "speed": 6.5, "attackRange": 100, "damage": 28, "tech": 9}'),
('inf_land125', 'LAND 125 Soldier (Australia)', 'infantry', 'future_soldier', '../images/infantry/infantry_land125.png', 'LAND 125, also known as the Soldier Combat System or Project Wundurra, is the Australian Defence Force''s program to modernize the individual infantry soldier and their squad.', '{"health": 130, "speed": 6.7, "attackRange": 95, "damage": 25, "tech": 8}'),
('inf_seal', 'Navy SEALs (USA)', 'infantry', 'special_forces', '../images/infantry/infantry_seal.png', 'Elite U.S. Navy special warfare operators specializing in sea, air, and land missions including direct action, special reconnaissance, counter-terrorism, and unconventional warfare.', '{"health": 120, "speed": 7.5, "attackRange": 105, "damage": 26, "versatility": 9}'),

-- ========== ARMOURED VEHICLES (PFVS) ==========
('pfv_kurganets', 'Kurganets-25 (Russia)', 'pfvs', 'ifv', '../images/pfv/pfv_kurganets.png', 'Next-generation infantry fighting vehicle platform with modular armor, advanced weapon systems including a 57mm autocannon, and enhanced protection against modern battlefield threats.', '{"health": 400, "speed": 8, "attackRange": 250, "damage": 75, "armor": 80}'),
('pfv_m113', 'M113 (USA)', 'pfvs', 'apc', '../images/pfv/pfv_m113.png', 'Versatile armored personnel carrier with aluminum armor, amphibious capabilities, and numerous variants used by militaries worldwide for troop transport.', '{"health": 250, "speed": 6.5, "attackRange": 120, "damage": 30, "capacity": 10}'),
('pfv_m2a3', 'Bradley M2A3 (USA)', 'pfvs', 'ifv', '../images/pfv/pfv_m2a3.png', 'Advanced infantry fighting vehicle with digital battlefield systems, improved armor protection, 25mm Bushmaster chain gun, and TOW missile system for combined arms warfare.', '{"health": 450, "speed": 7.5, "attackRange": 280, "damage": 85, "armor": 85}'),
('pfv_btr82a', 'BTR-82A (Russia)', 'pfvs', 'apc', '../images/pfv/pfv_82a.png', 'Modernized 8x8 wheeled armored personnel carrier with enhanced firepower, featuring a stabilized 30mm autocannon and improved protection system for urban combat operations.', '{"health": 350, "speed": 9, "attackRange": 220, "damage": 65, "mobility": 8}'),
('pfv_stryker', 'Stryker (USA)', 'pfvs', 'afv', '../images/pfv/pfv_stryker.png', '8x8 wheeled armored combat vehicle family with multiple variants, featuring advanced C4ISR systems, modular armor protection, and high strategic mobility for rapid deployment.', '{"health": 380, "speed": 8.5, "attackRange": 240, "damage": 70, "versatility": 9}'),
('pfv_pandur', 'Pandur II 8x8 PFV (Czech Republic)', 'pfvs', 'afv', '../images/pfv/pfv_pandur.png', 'Modular wheeled armored fighting vehicle with multiple weapon station options, including 30mm autocannon systems, designed for reconnaissance, fire support, and troop transport missions.', '{"health": 320, "speed": 8.2, "attackRange": 230, "damage": 68, "modularity": 8}'),
('pfv_mrap', 'MRAP All-Terrain Vehicle (USA)', 'pfvs', 'mrap', '../images/pfv/pfv_mrap.png', 'Mine-Resistant Ambush Protected vehicle designed with V-shaped hull for superior blast protection, featuring advanced armor and multiple weapon station options for counter-insurgency operations.', '{"health": 300, "speed": 7, "attackRange": 180, "damage": 45, "protection": 90}'),
('pfv_boxer', 'Boxer APC (Germany/Netherlands)', 'pfvs', 'apc', '../images/pfv/pfv_boxer.png', 'Modular 8x8 armored fighting vehicle with mission module flexibility, featuring advanced protection systems and multiple weapon configurations for various combat roles.', '{"health": 420, "speed": 7.8, "attackRange": 260, "damage": 78, "modularity": 9}'),
('pfv_guarani', 'VBTP-MR Guarani (Brazil)', 'pfvs', 'apc', '../images/pfv/pfv_guarani.png', '6x6 wheeled armored personnel carrier with modular design, amphibious capability, and multiple weapon station options for troop transport and combat support missions.', '{"health": 280, "speed": 8, "attackRange": 210, "damage": 60, "amphibious": 8}'),
('pfv_kaplan', 'Kaplan-30 (Turkey/Indonesia)', 'pfvs', 'ifv', '../images/pfv/pfv_kaplan.png', 'Modern medium-weight infantry fighting vehicle featuring a 30mm autocannon, anti-tank guided missiles, and advanced armor protection for enhanced battlefield survivability.', '{"health": 370, "speed": 7.2, "attackRange": 270, "damage": 80, "armor": 75}'),
('pfv_namer', 'Namer (Israel)', 'pfvs', 'apc', '../images/pfv/pfv_namer.png', 'Heavy armored personnel carrier based on Merkava tank chassis, featuring exceptional protection levels and designed to transport infantry safely in high-threat combat environments.', '{"health": 500, "speed": 6, "attackRange": 200, "damage": 65, "protection": 95}'),
('pfv_vn1', 'VN-1 (China)', 'pfvs', 'apc', '../images/pfv/pfv_vn1.png', '8x8 wheeled armored personnel carrier with modular design, amphibious capability, and multiple weapon configurations for troop transport and combat operations.', '{"health": 330, "speed": 8.3, "attackRange": 225, "damage": 67, "amphibious": 7}'),
('pfv_eitan', 'Eitan AFV (Israel)', 'pfvs', 'afv', '../images/pfv/pfv_eitan.png', 'Wheeled armored fighting vehicle featuring advanced protection systems, high mobility, and modular weapon stations designed for urban combat and counter-insurgency operations.', '{"health": 360, "speed": 8.8, "attackRange": 245, "damage": 72, "mobility": 9}'),
('pfv_ajax', 'Ajax AFV (UK)', 'pfvs', 'afv', '../images/pfv/pfv_ajax.png', 'Next-generation tracked armored fighting vehicle featuring advanced sensors, modular armor systems, and multiple variants for reconnaissance, direct fire, and engineering support roles.', '{"health": 430, "speed": 7, "attackRange": 290, "damage": 88, "sensors": 9}'),
('pfv_cv90', 'CV90 (Sweden)', 'pfvs', 'ifv', '../images/pfv/pfv_cv90.png', 'Highly versatile infantry fighting vehicle with exceptional mobility in Nordic terrain, featuring multiple weapon configurations including 30mm or 40mm autocannons and advanced protection systems.', '{"health": 410, "speed": 8.5, "attackRange": 275, "damage": 82, "mobility": 8}'),
('pfv_kf41', 'Lynx KF41 (Germany)', 'pfvs', 'ifv', '../images/pfv/pfv_kf41.png', 'Next-generation infantry fighting vehicle featuring modular armor, advanced sensor systems, and multiple weapon configurations including a 35mm or 50mm autocannon for enhanced lethality.', '{"health": 440, "speed": 7.8, "attackRange": 300, "damage": 90, "tech": 9}'),

-- ========== MAIN BATTLE TANKS (MBT) ==========
('mbts_abrams', 'M1A2 Abrams TUSK II', 'mbt', 'main_battle_tank', '../images/mbt/mbt_abrams.png', 'Advanced main battle tank featuring depleted uranium armor, 120mm smoothbore gun, and advanced fire control systems. The TUSK II variant adds urban warfare enhancements.', '{"health": 800, "speed": 5.5, "attackRange": 400, "damage": 150, "armor": 95}'),
('mbts_merkava', 'Merkava MK4', 'mbt', 'main_battle_tank', '../images/mbt/mbt_merkava.png', 'Israeli main battle tank with unique front-engine design for crew protection, modular armor, and Trophy active protection system against anti-tank missiles.', '{"health": 750, "speed": 5.8, "attackRange": 380, "damage": 145, "protection": 96}'),
('mbts_pl01', 'PL-01', 'mbt', 'stealth_tank', '../images/mbt/mbt_pl01.png', 'Polish stealth tank concept featuring advanced camouflage systems, modular weapon stations, and low radar signature design for modern battlefield operations.', '{"health": 600, "speed": 7, "attackRange": 350, "damage": 130, "stealth": 90}'),
('mbts_type99', 'Type 99/A', 'mbt', 'main_battle_tank', '../images/mbt/mbt_type99.png', 'Chinese third-generation main battle tank with 125mm smoothbore gun, laser countermeasures, and advanced composite armor for modern armored warfare.', '{"health": 780, "speed": 6, "attackRange": 390, "damage": 148, "armor": 92}'),

-- ========== TRANSPORTATION CATEGORY ==========
('transp_chinook', 'MH-47G Chinook (USA)', 'transportation', 'helicopter', '../images/transportation/transp_chinook.png', 'Heavy-lift helicopter capable of transporting troops, artillery, and vehicles in challenging environments.', '{"health": 350, "speed": 15, "capacity": 50, "range": 400, "transport": 95}'),
('transp_ch53', 'CH-53K Super Stallion (USA)', 'transportation', 'helicopter', '../images/transportation/transp_stallion.png', 'Heavy-lift helicopter designed to transport troops, vehicles, and supplies, even in hostile environments.', '{"health": 400, "speed": 14, "capacity": 55, "range": 450, "lift": 98}'),
('transp_blackhawk', 'UH-60 Black Hawk (USA)', 'transportation', 'helicopter', '../images/transportation/transp_hawk.png', 'Medium-lift utility helicopter used for troop transport, medical evacuation, and aerial assault missions with excellent performance in diverse environments.', '{"health": 250, "speed": 16, "capacity": 15, "range": 350, "versatility": 90}'),
('transp_mi17', 'Mi-17 Hip (Russia)', 'transportation', 'helicopter', '../images/transportation/transp_mi17.png', 'Versatile medium-transport helicopter used for troop transport, cargo delivery, and combat support with capability to operate in extreme weather conditions.', '{"health": 280, "speed": 13, "capacity": 30, "range": 380, "reliability": 85}'),
('transp_nh90', 'NH90 (Multi-National)', 'transportation', 'helicopter', '../images/transportation/transp_nh90.png', 'Advanced medium-sized, twin-engine multi-role military helicopter designed for troop transport, anti-submarine warfare, and search and rescue operations.', '{"health": 270, "speed": 15.5, "capacity": 20, "range": 420, "tech": 88}'),
('transp_v22', 'V-22 Osprey (USA)', 'transportation', 'tiltrotor', '../images/transportation/transp_osprey.png', 'Multi-mission, tiltrotor military aircraft with both vertical takeoff and landing (VTOL) and short takeoff and landing (STOL) capabilities.', '{"health": 320, "speed": 25, "capacity": 24, "range": 600, "speed": 95}'),
('transp_aw101', 'AW101 Merlin (UK/Italy)', 'transportation', 'helicopter', '../images/transportation/transp_aw101.png', 'Advanced multi-role helicopter designed for anti-submarine warfare, search and rescue, and troop transport operations in all weather conditions.', '{"health": 290, "speed": 14.5, "capacity": 30, "range": 430, "all_weather": 92}'),
('transp_c17', 'C-17 Globemaster III (USA)', 'transportation', 'strategic_airlift', '../images/transportation/transp_c17.png', 'Large military transport aircraft capable of rapid strategic delivery of troops and cargo to main operating bases or directly to forward bases.', '{"health": 500, "speed": 45, "capacity": 150, "range": 2500, "strategic": 98}'),
('transp_c130', 'C-130 Hercules (USA)', 'transportation', 'tactical_airlift', '../images/transportation/transp_c130.png', 'Versatile four-engine turboprop military transport aircraft capable of using unprepared runways for takeoffs and landings.', '{"health": 350, "speed": 35, "capacity": 90, "range": 2000, "tactical": 95}'),
('transp_c5', 'C-5 Galaxy (USA)', 'transportation', 'strategic_airlift', '../images/transportation/transp_c5.png', 'Massive strategic airlifter and one of the largest military aircraft in the world, capable of carrying oversized cargo across intercontinental ranges.', '{"health": 600, "speed": 40, "capacity": 270, "range": 3000, "capacity": 99}'),
('transp_a400m', 'A400M Atlas (Multinational)', 'transportation', 'tactical_airlift', '../images/transportation/transp_a400m.png', 'Advanced tactical and strategic airlifter with turboprop engines, capable of carrying heavy payloads and operating from rough, short airstrips.', '{"health": 420, "speed": 37, "capacity": 120, "range": 2200, "versatility": 92}'),
('transp_il76', 'Il-76 Candid (Russia)', 'transportation', 'strategic_airlift', '../images/transportation/transp_il76.png', 'Strategic and tactical airlifter with four turbofan engines, designed for heavy lifting and capable of operating from unpaved and rough airstrips.', '{"health": 380, "speed": 42, "capacity": 140, "range": 2400, "rough_field": 90}'),
('transp_y20', 'Y-20 Kunpeng (China)', 'transportation', 'strategic_airlift', '../images/transportation/transp_y20.png', 'Large military transport aircraft featuring advanced technologies and capable of carrying heavy payloads over long distances for strategic airlift operations.', '{"health": 450, "speed": 38, "capacity": 130, "range": 2300, "tech": 85}'),
('transp_an124', 'AN-124 Ruslan (Russia)', 'transportation', 'strategic_airlift', '../images/transportation/transp_an124.png', 'One of the world''s largest military transport aircraft, designed for strategic heavy airlift with massive payload capacity and a nose cargo door for efficient loading.', '{"health": 550, "speed": 39, "capacity": 350, "range": 2800, "payload": 99}'),
('transp_lhd', 'LHD 8 Makin Island (USA)', 'transportation', 'amphibious_assault', '../images/transportation/transp_lhd.png', 'Wasp-class amphibious assault ship featuring hybrid electric propulsion, capable of carrying Marines, aircraft, and landing craft for expeditionary operations.', '{"health": 1000, "speed": 12, "capacity": 2000, "range": 5000, "amphibious": 98}'),
('transp_071', 'LPD Amphibious Transport Dock Type 071 Yuzhao (China)', 'transportation', 'amphibious_transport', '../images/transportation/transp_071.png', 'Amphibious transport dock capable of carrying marines, vehicles, and landing craft for amphibious assault operations and humanitarian missions.', '{"health": 800, "speed": 14, "capacity": 800, "range": 4000, "amphibious": 90}'),
('transp_lcac', 'LCAC Hovercraft (USA)', 'transportation', 'hovercraft', '../images/transportation/transp_lcac.png', 'Landing Craft Air Cushion vehicle capable of high-speed amphibious transport over water, beach, and land obstacles for rapid deployment of troops and equipment.', '{"health": 200, "speed": 35, "capacity": 75, "range": 200, "amphibious": 95}'),
('transp_m1070', 'Oshkosh M1070 (USA)', 'transportation', 'heavy_transporter', '../images/transportation/transp_m1070.png', 'Heavy Equipment Transporter System (HETS) designed for transporting main battle tanks and other heavy armored vehicles, featuring exceptional payload capacity and off-road mobility.', '{"health": 180, "speed": 8, "capacity": 70, "range": 500, "payload": 96}'),
('transp_kamaz', 'KAMAZ 5350 (Russia)', 'transportation', 'military_truck', '../images/transportation/transp_kamaz.png', '4x4 multipurpose military truck designed for personnel transport, cargo delivery, and equipment towing in various terrain conditions with enhanced off-road capability and reliability.', '{"health": 120, "speed": 10, "capacity": 20, "range": 600, "off_road": 85}'),
('transp_v280', 'Bell V-280 Valor (USA)', 'transportation', 'tiltrotor', '../images/transportation/transp_v280.png', 'Third-generation tiltrotor aircraft offering enhanced speed, range, and agility for troop transport, medical evacuation, and combat support missions with significantly improved performance over conventional helicopters.', '{"health": 280, "speed": 28, "capacity": 14, "range": 500, "speed": 96}'),

-- ========== ARTILLERY CATEGORY ==========
('art_smerch', 'BM-30 Smerch (Russia)', 'artillery', 'mlrs', '../images/artillery/art_smerch.png', '300mm multiple launch rocket system with 12 launch tubes, capable of delivering devastating area bombardment at ranges up to 90km.', '{"health": 300, "speed": 4, "attackRange": 90000, "damage": 200, "area": 95}'),
('art_himars', 'M142 HIMARS (USA)', 'artillery', 'mlrs', '../images/artillery/art_himars.png', 'High Mobility Artillery Rocket System mounted on FMTV truck chassis, providing precision fire support with GPS-guided rockets and missiles.', '{"health": 250, "speed": 8, "attackRange": 300000, "damage": 180, "precision": 90}'),
('art_pzh2000', 'PzH 2000 (Germany)', 'artillery', 'self_propelled', '../images/artillery/art_pzh2000.png', 'Advanced self-propelled howitzer with fully automatic ammunition handling, capable of firing 10 rounds per minute with high accuracy.', '{"health": 320, "speed": 6, "attackRange": 40000, "damage": 150, "rate": 95}'),
('art_m109', 'M109A7 Paladin (USA)', 'artillery', 'self_propelled', '../images/artillery/art_m109.png', 'Latest variant of the M109 self-propelled howitzer with improved mobility, protection, and digital fire control systems.', '{"health": 280, "speed": 5.5, "attackRange": 30000, "damage": 140, "reliability": 88}'),

-- ========== ANTI-AIRCRAFT (AAS) CATEGORY ==========
('aas_pantsir', 'Pantsir-S1 (Russia)', 'aas', 'spaag', '../images/aas/aas_pantsir.png', 'Combined short to medium range surface-to-air missile and anti-aircraft artillery system mounted on a tracked chassis.', '{"health": 220, "speed": 5, "attackRange": 20000, "damage": 120, "anti_air": 95}'),
('aas_patriot', 'MIM-104 Patriot (USA)', 'aas', 'sam', '../images/aas/aas_patriot.png', 'Long-range air defense system capable of engaging aircraft, cruise missiles, and tactical ballistic missiles.', '{"health": 180, "speed": 0, "attackRange": 160000, "damage": 180, "range": 98}'),
('aas_iron_dome', 'Iron Dome (Israel)', 'aas', 'c-ram', '../images/aas/aas_irondome.png', 'Mobile all-weather air defense system designed to intercept and destroy short-range rockets and artillery shells.', '{"health": 150, "speed": 8, "attackRange": 70000, "damage": 100, "interception": 96}'),
('aas_s400', 'S-400 Triumf (Russia)', 'aas', 'sam', '../images/aas/aas_s400.png', 'Long-range surface-to-air missile system capable of engaging aircraft, UAVs, and ballistic missiles at extreme ranges.', '{"health": 200, "speed": 0, "attackRange": 400000, "damage": 200, "range": 99}'),

-- ========== HELICOPTERS CATEGORY ==========
('hel_apache', 'AH-64 Apache (USA)', 'helicopters', 'attack', '../images/helicopters/hel_apache.png', 'Twin-turboshaft attack helicopter with nose-mounted sensor suite for target acquisition and night vision systems.', '{"health": 300, "speed": 18, "attackRange": 8000, "damage": 160, "attack": 95}'),
('hel_ka52', 'Ka-52 Alligator (Russia)', 'helicopters', 'attack', '../images/helicopters/hel_ka52.png', 'Coaxial twin-seat attack helicopter with advanced avionics, all-weather capability, and anti-armor weapons.', '{"health": 280, "speed": 17, "attackRange": 7500, "damage": 155, "agility": 90}'),
('hel_mi28', 'Mi-28 Havoc (Russia)', 'helicopters', 'attack', '../images/helicopters/hel_mi28.png', 'Heavy attack helicopter designed for anti-tank operations with advanced targeting systems and heavy armor protection.', '{"health": 320, "speed": 16, "attackRange": 8500, "damage": 165, "armor": 88}'),
('hel_tiger', 'Eurocopter Tiger (EU)', 'helicopters', 'attack', '../images/helicopters/hel_tiger.png', 'Multirole attack helicopter with composite materials, advanced stealth features, and modern avionics suite.', '{"health": 260, "speed": 19, "attackRange": 7800, "damage": 150, "stealth": 85}'),

-- ========== FIGHTER JETS CATEGORY ==========
('fj_f35', 'F-35 Lightning II (USA)', 'fighterjets', 'multirole', '../images/fighterjets/fj_f35.png', 'Fifth-generation single-seat, single-engine stealth multirole combat aircraft designed for ground-attack and air-superiority missions.', '{"health": 400, "speed": 65, "attackRange": 100000, "damage": 200, "stealth": 98}'),
('fj_f22', 'F-22 Raptor (USA)', 'fighterjets', 'air_superiority', '../images/fighterjets/fj_f22.png', 'Fifth-generation air superiority fighter with advanced stealth, sensor fusion, and supercruise capability.', '{"health": 380, "speed": 70, "attackRange": 120000, "damage": 180, "air_superiority": 99}'),
('fj_su57', 'Su-57 Felon (Russia)', 'fighterjets', 'multirole', '../images/fighterjets/fj_su57.png', 'Fifth-generation multirole fighter aircraft featuring stealth technology, supermaneuverability, and advanced avionics.', '{"health": 390, "speed": 68, "attackRange": 110000, "damage": 190, "maneuverability": 96}'),
('fj_j20', 'Chengdu J-20 (China)', 'fighterjets', 'air_superiority', '../images/fighterjets/fj_j20.png', 'Fifth-generation stealth air superiority fighter with canard delta wings and advanced sensor suite for long-range engagements.', '{"health": 370, "speed": 66, "attackRange": 105000, "damage": 185, "stealth": 92}'),

-- ========== BOMBER CATEGORY ==========
('bom_b2', 'B-2 Spirit (USA)', 'bomber', 'stealth', '../images/bomber/bom_b2.png', 'Strategic stealth bomber capable of delivering both conventional and nuclear weapons with low observable technology.', '{"health": 500, "speed": 55, "attackRange": 11000, "damage": 300, "stealth": 99}'),
('bom_b52', 'B-52 Stratofortress (USA)', 'bomber', 'strategic', '../images/bomber/bom_b52.png', 'Long-range, subsonic strategic bomber capable of carrying large payloads of conventional and nuclear ordnance.', '{"health": 450, "speed": 50, "attackRange": 14100, "damage": 280, "payload": 98}'),
('bom_tu160', 'Tu-160 Blackjack (Russia)', 'bomber', 'strategic', '../images/bomber/bom_tu160.png', 'Supersonic variable-sweep wing heavy strategic bomber and missile platform with intercontinental range.', '{"health": 480, "speed": 60, "attackRange": 12300, "damage": 290, "speed": 95}'),
('bom_tu95', 'Tu-95 Bear (Russia)', 'bomber', 'strategic', '../images/bomber/bom_tu95.png', 'Large, four-engine turboprop-powered strategic bomber and missile platform with distinctive contra-rotating propellers.', '{"health": 420, "speed": 45, "attackRange": 15000, "damage": 260, "range": 99}'),

-- ========== DESTROYERS CATEGORY ==========
('des_arliegh', 'Arleigh Burke-class (USA)', 'destroyers', 'guided_missile', '../images/destroyers/des_arliegh.png', 'Multi-mission guided missile destroyer equipped with Aegis Combat System for air defense, ballistic missile defense, and anti-submarine warfare.', '{"health": 800, "speed": 30, "attackRange": 250000, "damage": 350, "versatility": 95}'),
('des_type55', 'Type 055 (China)', 'destroyers', 'guided_missile', '../images/destroyers/des_type55.png', 'Chinese guided missile destroyer featuring advanced radar systems, VLS cells, and multi-role combat capabilities.', '{"health": 850, "speed": 32, "attackRange": 240000, "damage": 340, "tech": 90}'),
('des_daring', 'Type 45 Daring-class (UK)', 'destroyers', 'air_defense', '../images/destroyers/des_daring.png', 'Air defense destroyer equipped with Sea Viper missile system and advanced radar for fleet air defense missions.', '{"health": 780, "speed": 29, "attackRange": 230000, "damage": 320, "air_defense": 96}'),
('des_kolkata', 'Kolkata-class (India)', 'destroyers', 'guided_missile', '../images/destroyers/des_kolkata.png', 'Stealth-guided missile destroyer featuring advanced indigenous weapon systems and sensor suites.', '{"health": 820, "speed": 31, "attackRange": 220000, "damage": 330, "stealth": 85}'),

-- ========== CARRIER CATEGORY ==========
('car_nimitz', 'Nimitz-class (USA)', 'carrier', 'supercarrier', '../images/carrier/car_nimitz.png', 'Nuclear-powered supercarrier capable of carrying over 60 aircraft, serving as the centerpiece of carrier strike groups.', '{"health": 1500, "speed": 30, "capacity": 90, "range": "unlimited", "air_wing": 99}'),
('car_ford', 'Gerald R. Ford-class (USA)', 'carrier', 'supercarrier', '../images/carrier/car_ford.png', 'Latest generation of supercarriers featuring electromagnetic aircraft launch system and advanced systems automation.', '{"health": 1600, "speed": 32, "capacity": 75, "range": "unlimited", "tech": 98}'),
('car_liaoning', 'Liaoning (China)', 'carrier', 'aircraft_carrier', '../images/carrier/car_liaoning.png', 'Chinese aircraft carrier converted from Soviet Kuznetsov-class, serving as a training platform and power projection asset.', '{"health": 1200, "speed": 29, "capacity": 50, "range": 8000, "training": 85}'),
('car_queen', 'Queen Elizabeth-class (UK)', 'carrier', 'aircraft_carrier', '../images/carrier/car_queen.png', 'Largest warship ever built for the Royal Navy, featuring STOVL operations for F-35B aircraft.', '{"health": 1300, "speed": 31, "capacity": 70, "range": 10000, "stovl": 92}');